"""add document versioning

Revision ID: 10905760c429
Revises: 96ec9d084aae
Create Date: 2026-07-29 17:09:07.217144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10905760c429'
down_revision: Union[str, Sequence[str], None] = '96ec9d084aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('documents', sa.Column('previous_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'documents', ['previous_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'previous_version_id')
    op.drop_column('documents', 'version')
    # ### end Alembic commands ###
